OFFLINE_IL_CONFIGS = {
  "HALFCHEETAH_ONAIL": {
    "il_demo_path": ["data/halfcheetah_demos.npz"],
    "env_name": ["HalfCheetah-v2"],

    "path": "/tmp/logs/ONAIL",
    "max_iter": int(1e7),
    "il_max_demos": 20,
    "seed": 0,
    "il_gamma": 0.99,
    "il_ent_coef": 0.,
    "il_batch_size": 256,

    "Q_layers": [256, 256],
    "policy_layers": [256, 256],
    "il_nu_gradient_penalty": 0.,

    "il_use_donsker_varadhan_for_pi_update": False,
    "il_kl_factor": 1.,
    "il_policy_learning_rate": 1e-4,
     "il_Q_learning_rate": 1e-3,
    "il_num_nu_steps": 1000,
    "il_num_policy_steps": 10000,
  },
  "HALFCHEETAH_VDICE": {
    "il_demo_path": ["data/halfcheetah_demos.npz"],
    "env_name": ["HalfCheetah-v2"],

    "path": "/tmp/logs/ONAIL",
    "max_iter": int(1e7),
    "il_max_demos": 20,
    "seed": 0,
    "il_gamma": 0.99,
    "il_ent_coef": 0.,
    "il_batch_size": 256,

    "Q_layers": [256, 256],
    "policy_layers": [256, 256],
    "il_nu_gradient_penalty": 0.,

    "il_use_donsker_varadhan_for_pi_update": True,
    "il_kl_factor": 0.,
    "il_policy_learning_rate": 1e-5,
    "il_Q_learning_rate": 1e-3,
    "il_num_nu_steps": 5,
    "il_num_policy_steps": 1,
  },
  "ANT_ONAIL": {
      "il_demo_path": ["data/ant_demos.npz"],
      "env_name": ["AntNoEarlyTerm-v3"],

      "path": "/tmp/logs/ONAIL",
      "max_iter": int(1e7),
      "il_max_demos": 20,
      "seed": 0,
      "il_gamma": 0.99,
      "il_ent_coef": 0.,
      "il_batch_size": 256,

      "Q_layers": [256, 256],
      "policy_layers": [256, 256],
      "il_nu_gradient_penalty": 0.,

      "il_use_donsker_varadhan_for_pi_update": False,
      "il_kl_factor": 1.,
      "il_policy_learning_rate": 1e-4,
      "il_Q_learning_rate": 1e-3,
      "il_num_nu_steps": 1000,
      "il_num_policy_steps": 10000,
  },
  "ANT_VDICE": {
    "il_demo_path": ["data/ant_demos.npz"],
    "env_name": ["AntNoEarlyTerm-v3"],

    "path": "/tmp/logs/ONAIL",
    "max_iter": int(1e7),
    "il_max_demos": 20,
    "seed": 0,
    "il_gamma": 0.99,
    "il_ent_coef": 0.,
    "il_batch_size": 256,

    "Q_layers": [256, 256],
    "policy_layers": [256, 256],
    "il_nu_gradient_penalty": 0.,

    "il_use_donsker_varadhan_for_pi_update": True,
    "il_kl_factor": 0.,
    "il_policy_learning_rate": 1e-5,
    "il_Q_learning_rate": 1e-3,
    "il_num_nu_steps": 5,
    "il_num_policy_steps": 1,
  },
  "WALKER_ONAIL": {
      "il_demo_path": ["data/walker_demos.npz"],
      "env_name": ["WalkerNoEarlyTerm-v3"],

      "path": "/tmp/logs/ONAIL",
      "max_iter": int(1e7),
      "il_max_demos": 20,
      "seed": 0,
      "il_gamma": 0.99,
      "il_ent_coef": 0.,
      "il_batch_size": 256,

      "Q_layers": [256, 256],
      "policy_layers": [256, 256],
      "il_nu_gradient_penalty": 0.,

      "il_use_donsker_varadhan_for_pi_update": False,
      "il_kl_factor": 1.,
      "il_policy_learning_rate": 1e-4,
      "il_Q_learning_rate": 1e-3,
      "il_num_nu_steps": 1000,
      "il_num_policy_steps": 10000,
  },
  "WALKER_VDICE": {
    "il_demo_path": ["data/walker_demos.npz"],
    "env_name": ["WalkerNoEarlyTerm-v3"],

    "path": "/tmp/logs/ONAIL",
    "max_iter": int(1e7),
    "il_max_demos": 20,
    "seed": 0,
    "il_gamma": 0.99,
    "il_ent_coef": 0.,
    "il_batch_size": 256,

    "Q_layers": [256, 256],
    "policy_layers": [256, 256],
    "il_nu_gradient_penalty": 0.,

    "il_use_donsker_varadhan_for_pi_update": True,
    "il_kl_factor": 0.,
    "il_policy_learning_rate": 1e-5,
    "il_Q_learning_rate": 1e-3,
    "il_num_nu_steps": 5,
    "il_num_policy_steps": 1,
  },
  "HOPPER_ONAIL": {
      "il_demo_path": ["data/hopper_demos.npz"],
      "env_name": ["HopperNoEarlyTerm-v3"],

      "path": "/tmp/logs/ONAIL",
      "max_iter": int(1e7),
      "il_max_demos": 20,
      "seed": 0,
      "il_gamma": 0.99,
      "il_ent_coef": 0.,
      "il_batch_size": 256,

      "Q_layers": [256, 256],
      "policy_layers": [256, 256],
      "il_nu_gradient_penalty": 0.,

      "il_use_donsker_varadhan_for_pi_update": False,
      "il_kl_factor": 1.,
      "il_policy_learning_rate": 1e-4,
      "il_Q_learning_rate": 1e-3,
      "il_num_nu_steps": 1000,
      "il_num_policy_steps": 10000,
  },
  "HOPPER_VDICE": {
    "il_demo_path": ["data/hopper_demos.npz"],
    "env_name": ["HopperNoEarlyTerm-v3"],

    "path": "/tmp/logs/ONAIL",
    "max_iter": int(1e7),
    "il_max_demos": 20,
    "seed": 0,
    "il_gamma": 0.99,
    "il_ent_coef": 0.,
    "il_batch_size": 256,

    "Q_layers": [256, 256],
    "policy_layers": [256, 256],
    "il_nu_gradient_penalty": 0.,

    "il_use_donsker_varadhan_for_pi_update": True,
    "il_kl_factor": 0.,
    "il_policy_learning_rate": 1e-5,
    "il_Q_learning_rate": 1e-3,
    "il_num_nu_steps": 5,
    "il_num_policy_steps": 1,
  }
}